### ISSUE TITLE
Implement rate limiting best practices for GitHub

### ISSUE THREAD

**Issue by moorara** [moorara/changelog#17]
## Context

Currently, for large number of issues and pull requests, we get blocked by GitHub:
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits

```
Status Code: 403
Body: 403: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

### Expected Behavior

Best practices for rate limiting requests to GitHub should be observed. And we should not get the above error when generating the changelog for existing repos with a large history.

### Proposed Solution

We should implemented the best practices described here:

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
https://docs.github.com/en/rest/reference/rate-limit
https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits

#### TODO:

  - [x] Make authenticated request
  - [ ] Make request for the same authenticated user serially or with a maximum concurrent threshold
  - [ ] Check `Retry-After` response header on every request and stall next requests if needed
